# https://github.com/repository-settings/app
_extends: .github
repository:
  name: vercel-cron
  private: false
branches:
  - name: main
    protection:
      required_status_checks:
        contexts:
          - Build
          - Lint
          - Test
